apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-vm-manager-chart.fullname" . }}-repo-envvar
  labels:
  {{- include "finops-operator-vm-manager-chart.labels" . | nindent 4 }}
data:
  REPO: {{ .Values.repoEnvvarConfigmapVMManager.repo | quote }}
