apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-operator-vm-manager-chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-vm-manager
    app.kubernetes.io/part-of: operator-vm-manager
  {{- include "finops-operator-vm-manager-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}